env: road_marl

env_args:
  env_type: "CologneBonnDusseldorf-v1"
  discount_reward: 1.0
  state_obs: True
  obs_multiple: False
  reward_normalization: 100000.0

learner_log_interval: 100
log_interval: 1000
runner_log_interval: 50
test_interval: 1000
test_nepisode: 1
test_greedy: True
t_max: 58752000 
save_model: False
save_model_interval: 50000